### ISSUE TITLE
Accessibility Review

### ISSUE THREAD

**Issue by FatimaZelay** [DivaniNL/all-human-accessible-website#18]
De accessibility van je website is 85 dat is goed. De namen van jou buttons zijn niet toegankelijk, probeer simpele namen en anders aria-label te gebruiken.  Bij het gebruiken van de tab-index slaat het de nieuwsbrief en de zoekbar knopjes over. Bij de pop-up werkt werkt de tab-index ook niet.

**Comment by DivaniNL** [comment]
Goed gezien. Dankjewel voor de feedback. Dit probleem was bij mij al bekend, alleen nog geen tijd gehad om het op te lossen. Zie issue: [https://github.com/DivaniNL/all-human-accessible-website/issues/12](https://github.com/DivaniNL/all-human-accessible-website/issues/12)

**Comment by DivaniNL** [comment]
Alle problemen zijn opgelost
[Hier heb ik een functie toegevoegd zodat na het openen van een popup, de elementen hierin tab-baar zijn](https://github.com/DivaniNL/all-human-accessible-website/commit/bfdb637505b4b15ba5e5b51951c2830191a02c66#diff-68e5fc69a6a980a801fd0d1f8a8c78fdf84a7d0a13ae3d9555306935023cefa2R84-R104)
[Hier heb ik aria-label toegevoegd](https://github.com/DivaniNL/all-human-accessible-website/commit/d7a978a460c790faf069c6b38f02747d0288e82c#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L143-L394)
